services:
  - type: web
    name: logic-theorist-call-center-madness-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CLIENT_URL
        sync: false
      - key: APPS_SCRIPT_URL
        sync: false
